export const puzzleMocks = [
  {
    audio: 'files/16_0310.mp3',
    audioExample: 'files/16_0310_example.mp3',
    audioMeaning: 'files/16_0310_meaning.mp3',
    group: 0,
    id: '5e9f5ee35eb9e72bc21af5d5',
    image: 'files/16_0310.jpg',
    page: 15,
    textExample: 'Chris studies <b>from</b> 10 o’clock to noon every morning.',
    textExampleTranslate: 'Крис учится с 10 до 12 часов каждое утро',
    textMeaning: '<i>From</i> shows a starting place or position.',
    textMeaningTranslate: 'От показывает начальное место или позицию',
    transcription: '[frəm]',
    word: 'from',
    wordTranslate: 'от',
    wordsPerExampleSentence: 9,
  },
  {
    audio: 'files/16_0306.mp3',
    audioExample: 'files/16_0306_example.mp3',
    audioMeaning: 'files/16_0306_meaning.mp3',
    group: 0,
    id: '5e9f5ee35eb9e72bc21af5d1',
    image: 'files/16_0306.jpg',
    page: 15,
    textExample: 'I had a hamburger for <b>dinner</b>.',
    textExampleTranslate: 'У меня был гамбургер на ужин',
    textMeaning: '<i>Dinner</i> is the main meal eaten in the evening.',
    textMeaningTranslate: 'Ужин - основная еда, которую едят вечером',
    transcription: '[dínər]',
    word: 'dinner',
    wordTranslate: 'обед',
    wordsPerExampleSentence: 6,
  },
  {
    audio: 'files/10_1984.mp3',
    audioExample: 'files/10_1984_example.mp3',
    audioMeaning: 'files/10_1984_meaning.mp3',
    group: 3,
    id: '5e9f5ee35eb9e72bc21afc60',
    image: 'files/10_1984.jpg',
    page: 9,
    textExample: 'When the bank <b>automated</b>, it started installing ATM machines.',
    textExampleTranslate: 'Когда банк автоматизировался, он начал устанавливать банкоматы',
    textMeaning: 'To <i>automate</i> something means to have machines or computers do the work.',
    textMeaningTranslate: 'Автоматизировать что-то означает, что машины или компьютеры выполняют свою работу',
    transcription: '[ɔ́ːtəmèit]',
    word: 'automate',
    wordTranslate: 'автоматизировать',
    wordsPerExampleSentence: 9,
  },
  {
    audio: 'files/21_2216.mp3',
    audioExample: 'files/21_2216_example.mp3',
    audioMeaning: 'files/21_2216_meaning.mp3',
    group: 3,
    id: '5e9f5ee35eb9e72bc21afd47',
    image: 'files/21_2216.jpg',
    page: 20,
    textExample: 'The store sold their <b>surplus</b> items on sale.',
    textExampleTranslate: 'Магазин продал свои излишки на распродаже',
    textMeaning: 'A <i>surplus</i> is an extra amount of something.',
    textMeaningTranslate: 'Избыток - это дополнительное количество чего-то',
    transcription: '[sə́ːrplʌs]',
    word: 'surplus',
    wordTranslate: 'излишки',
    wordsPerExampleSentence: 8,
  },
  {
    audio: 'files/21_2220.mp3',
    audioExample: 'files/21_2220_example.mp3',
    audioMeaning: 'files/21_2220_meaning.mp3',
    group: 3,
    id: '5e9f5ee35eb9e72bc21afd4b',
    image: 'files/21_2220.jpg',
    page: 20,
    textExample: 'Henry uses <b>vigorous</b> exercise to keep himself in shape.',
    textExampleTranslate: 'Генри использует энергичные упражнения, чтобы держать себя в форме',
    textMeaning: 'If something or someone is <i>vigorous</i>, they use a lot of energy.',
    textMeaningTranslate: 'Если что-то или кто-то энергичный, они используют много энергии',
    transcription: '[vígərəs]',
    word: 'vigorous',
    wordTranslate: 'энергичный',
    wordsPerExampleSentence: 9,
  },
  {
    audio: 'files/21_2218.mp3',
    audioExample: 'files/21_2218_example.mp3',
    audioMeaning: 'files/21_2218_meaning.mp3',
    group: 3,
    id: '5e9f5ee35eb9e72bc21afd49',
    image: 'files/21_2218.jpg',
    page: 20,
    textExample: 'They enjoyed <b>theorizing</b> about how things worked.',
    textExampleTranslate: 'Они наслаждались рассуждениями о том, как все работает',
    textMeaning: 'To <i>theorize</i> means to develop ideas about something.',
    textMeaningTranslate: 'Теоретизировать означает развивать идеи о чем-то',
    transcription: '[θíːəràiz]',
    word: 'theorize',
    wordTranslate: 'теоретизировать',
    wordsPerExampleSentence: 7,
  },
  {
    audio: 'files/08_1944.mp3',
    audioExample: 'files/08_1944_example.mp3',
    audioMeaning: 'files/08_1944_meaning.mp3',
    group: 3,
    id: '5e9f5ee35eb9e72bc21afc37',
    image: 'files/08_1944.jpg',
    page: 7,
    textExample: 'The doctor diagnosed the patient with <b>epilepsy</b>.',
    textExampleTranslate: 'Врач поставил диагноз пациенту с эпилепсией',
    textMeaning: '<i>Epilepsy</i> is a medical condition that affects the brain and can make someone become unconscious or unable to control their movement for a short time.',
    textMeaningTranslate: 'Эпилепсия - это заболевание, которое влияет на мозг и может привести к тому, что кто-то потеряет сознание или не сможет в течение короткого времени контролировать свои движения',
    transcription: '[épəlèpsi]',
    word: 'epilepsy',
    wordTranslate: 'эпилепсия',
    wordsPerExampleSentence: 7,
  },
  {
    audio: 'files/08_1959.mp3',
    audioExample: 'files/08_1959_example.mp3',
    audioMeaning: 'files/08_1959_meaning.mp3',
    group: 3,
    id: '5e9f5ee35eb9e72bc21afc46',
    image: 'files/08_1959.jpg',
    page: 7,
    textExample: 'Pasta is high in <b>starch</b>.',
    textExampleTranslate: 'Макароны с высоким содержанием крахмала',
    textMeaning: '<i>Starch</i> is a substance that provides your body with energy and is found in foods such as wheat, potatoes, and rice.',
    textMeaningTranslate: 'Крахмал - это вещество, которое обеспечивает ваше тело энергией и содержится в таких продуктах, как пшеница, картофель и рис',
    transcription: '[staːrʧ]',
    word: 'starch',
    wordTranslate: 'крахмал',
    wordsPerExampleSentence: 5,
  },
  {
    audio: 'files/08_1960.mp3',
    audioExample: 'files/08_1960_example.mp3',
    audioMeaning: 'files/08_1960_meaning.mp3',
    group: 3,
    id: '5e9f5ee35eb9e72bc21afc47',
    image: 'files/08_1960.jpg',
    page: 7,
    textExample: 'Cindy concluded the meeting with a <b>summary</b> of the project.',
    textExampleTranslate: 'Синди завершила встречу с кратким изложением проекта',
    textMeaning: 'A <i>summary</i> is a short statement that contains the main information about something.',
    textMeaningTranslate: 'Резюме - это краткое изложение, которое содержит основную информацию о чем-либо',
    transcription: '[sΛməri]',
    word: 'summary',
    wordTranslate: 'резюме',
    wordsPerExampleSentence: 10,
  }, {
    audio: 'files/15_0890.mp3',
    audioExample: 'files/15_0890_example.mp3',
    audioMeaning: 'files/15_0890_meaning.mp3',
    group: 1,
    id: '5e9f5ee35eb9e72bc21af819',
    image: 'files/15_0890.jpg',
    page: 14,
    textExample: 'We <b>donate</b> money to charities every year.',
    textExampleTranslate: 'Мы жертвуем деньги благотворительным организациям каждый год',
    textMeaning: 'To <i>donate</i> is to give something to a charity or organization.',
    textMeaningTranslate: 'Пожертвовать - значит дать что-то благотворительной организации или организации',
    transcription: '[dóuneit]',
    word: 'donate',
    wordTranslate: 'пожертвовать',
    wordsPerExampleSentence: 7,
  },
];
